name: Validate documentation PR

on:
  pull_request:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/deploy-docs.yaml
      - .github/workflows/validate-docs-pr.yaml

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: pnpm install

      - name: Run markdownlint
        working-directory: docs
        run: pnpm lint

      - name: Build Docs
        working-directory: docs
        run: pnpm build
